
name: First Flask CI

on:
  push:
    branches:
      - main  # Change to 'master' if your default branch is named that

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Confirm setup
        run: echo "Flask app environment ready!"
