# name: First Flask CI

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run tests
#         run: pytest

name: First Flask CI + Temporary Local Run

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Start Flask for testing (auto-stop)
        run: |
          flask run --host=127.0.0.1 --port=5000 &
          FLASK_PID=$!
          sleep 5
          echo "Testing Flask response..."
          curl --fail http://127.0.0.1:5000 || (echo "Flask did not respond" && kill $FLASK_PID && exit 1)
          sleep 20
          kill $FLASK_PID
          echo "Flask stopped."
